connector.name=trino
connection-url=jdbc:trino://trino-remote-basic:8080/memory
connection-user=trino
join-pushdown.enabled=true
join-pushdown.strategy=EAGER
remote-delegation.enabled=true
unsupported-type-handling=CONVERT_TO_VARCHAR
