#!/usr/bin/env bash
set -euo pipefail

repository="${GITHUB_REPOSITORY:-kkd927/trino2trino}"
github_host="${GITHUB_SERVER_URL:-https://github.com}"
github_host="${github_host#https://}"
github_host="${github_host#http://}"
output="${1:-RELEASES.md}"
release_rows="$(mktemp)"
latest_rows="$(mktemp)"
tab=$'\t'
trap 'rm -f "${release_rows}" "${latest_rows}"' EXIT

gh api --hostname "${github_host}" --paginate "repos/${repository}/releases" \
    --jq '.[] | select((.draft | not) and (.prerelease | not) and (.tag_name | test("^trino-[0-9]+-r[0-9]+$"))) | [.tag_name, .html_url] | @tsv' \
    > "${release_rows}"

sed -E 's/^trino-([0-9]+)-r([0-9]+)	(.*)$/\1	\2	trino-\1-r\2	\3/' "${release_rows}" \
    | sort -t "${tab}" -k1,1nr -k2,2nr \
    | awk -F '\t' '!seen[$1]++ { print $1 "\t" $3 "\t" $4 }' \
    > "${latest_rows}"

if [[ ! -s "${latest_rows}" ]]; then
    echo "No trino-<version>-r<revision> releases found for ${repository}." >&2
    exit 1
fi

{
    cat <<'EOF'
# Supported Trino Releases

<!-- This file is generated by .github/scripts/update-supported-releases.sh. -->

trino2trino artifacts are built for a specific Trino version. Choose the row
matching your local Trino server version, open the release, and download the
plugin ZIP asset.

Do not rely on GitHub's global "Latest" badge when selecting an artifact. Use
the release that matches your Trino version.

| Trino version | Latest trino2trino release | Plugin ZIP |
|---------------|----------------------------|------------|
EOF

    while IFS=$'\t' read -r version tag url; do
        printf '| %s | [%s](%s) | `%s` |\n' "${version}" "${tag}" "${url}" "trino-trino-${version}.zip"
    done < "${latest_rows}"
} > "${output}"
